### PR TITLE
Fixed line changing issue for rules

### LINKED ISSUE #5: Displaying Formatted text for Rules.
Rules are just displayed in a single TextView with no formatting. Basically, just the raw data fetched is displayed as it is.

**Use String Buffer** modify the data coming from Database. the `\n` is the break point for the new rule.
**Use a Adapter class** (if Required)
and display the rules in a textViews which are to be displayed in Recycler view.

### Files to work on
[layout_rules.xml](https://github.com/IIITDMJ-OPEN-SOURCE/Technical-Fest/blob/master/app/src/main/res/layout/rules_layout.xml)
[EventInfoActivity.java](https://github.com/IIITDMJ-OPEN-SOURCE/Technical-Fest/blob/master/app/src/main/java/com/priyanshnama/technical_fest/ui/events/EventInfoActivity.java)

### PR DESCRIPTION
**Pull request by kartik-pant-23**
# Description
Fixed the issue of showing rules with line breaks. Added a StringFormatter class for this function. Also added the textView in rules layout inside the ScrollView for properly shoeing the data.

# Fixes
Now the rule layout works perfectly fine with scrolling and text formatting.

### CODE REVIEW

**Comment by priyanshnama** [comment]
@kartik-pant-23 
### Thanks for Contributing and working on this issue.
But we wanted the **use of RecyclerView**. because,
each time `/n` appears the the line is to be shown in a new textView so, **we can't hardcore 1 textView.**.

So, pass each line to a new TextView in the RecyclerView.

**Comment by priyanshnama** [comment]
and do provide the screenshot showing the changes made and state of app.

**Comment by kartik-pant-23** [comment]
rulesLayout

**Comment by kartik-pant-23** [comment]
As of now encountering two line breaks seems a more legit thing to make use of a new textView in a recyclerView and i will try doing that. Thank you for your feedback.

**Comment by priyanshnama** [comment]
Ya.
I think we should implemet this for now.
Basically i wanted to add shadow to each textView and custom background.
But we can do this later.
**Thanks for Contributing.** @kartik-pant-23

**Comment by kartik-pant-23** [comment]
Thank you for merging the pull request, I still would try to bring about the change you probably wanted. Thanks a lot!

**Pull request merged**
